package corbaBanque;


/**
* corbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from banque.idl
* Friday, December 3, 2021 11:11:26 AM CET
*/

public interface IBanqueRemoteOperations 
{
  double connversion (double montant);
} // interface IBanqueRemoteOperations
